### PR TITLE
Added Contributing Steps

### LINKED ISSUE #3: Add contributing steps
Add contributing steps and guidelines

### PR DESCRIPTION
**Pull request by ampsteric**
resolved #3.
please review and accept the PR and accept my contribution for GitProfile and Hactoberfest.

best regards,
ampsteric

### CODE REVIEW

**Review by chavarera — APPROVED** [review]

**Review by AdityaJ7 — COMMENTED** [review]
Good job

**Review by tusharnankani — COMMENTED** [review]
Good work! 👍🏻

**Comment by ampsteric** [comment]
Thanks a lot for appreciating my work and helping me make my first PR for my first hacktoberfest @chavarera @AdityaJ7 @tusharnankani

**Comment by ampsteric** [comment]
It is my humble request to the maintainers to please label my PR as "hacktoberfest-accepted" or mark the repo with the "hacktoberfest"  topic so that it can be counted as a valid PR for my first hacktoberfest.

best regards,
ampsteric

**Pull request merged**
